# Generated by Django 5.0.2 on 2024-02-11 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0001_initial'),
        ('frutas', '0003_alter_fruta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruta',
            name='cor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cores.cor'),
        ),
    ]
